### ISSUE TITLE
"tmsu config" allows invalid config values, leading to panics

### ISSUE THREAD

**Issue by ipkiss42** [oniony/TMSU#202]
Simple example:

```sh
$ tmsu init
# This should fail, but it doesn't
$ tmsu config autoCreateTags=garbage
# Now the DB settings are invalid and things can go wrong
$ tmsu tag . new_tag
panic: invalid boolean value

goroutine 1 [running]:
github.com/oniony/TMSU/entities.Settings.BoolValue(0xc000126280, 0x9, 0xa, 0x71d75e, 0xe, 0xc000010100)
        /home/ipkiss/.cache/yay/tmsu/src/TMSU-0.7.5/src/github.com/oniony/TMSU/entities/setting.go:90 +0x195
github.com/oniony/TMSU/entities.Settings.AutoCreateTags(...)
        /home/ipkiss/.cache/yay/tmsu/src/TMSU-0.7.5/src/github.com/oniony/TMSU/entities/setting.go:38
github.com/oniony/TMSU/cli.parseTagValuePairs(0xc000074750, 0xc000010100, 0xc000126280, 0x9, 0xa, 0xc00000e230, 0x1, 0x1, 0xc000112500, 0x0, ...)
        /home/ipkiss/.cache/yay/tmsu/src/TMSU-0.7.5/src/github.com/oniony/TMSU/cli/tag.go:424 +0x684
github.com/oniony/TMSU/cli.tagPaths(0xc000074750, 0xc000010100, 0xc00000e230, 0x1, 0x1, 0xc00000e220, 0x1, 0x2, 0x1000000, 0xc00001c180, ...)
        /home/ipkiss/.cache/yay/tmsu/src/TMSU-0.7.5/src/github.com/oniony/TMSU/cli/tag.go:199 +0x12b
github.com/oniony/TMSU/cli.tagExec(0x9492d0, 0x0, 0x0, 0xc00000e220, 0x2, 0x2, 0xc00001c180, 0x23, 0x0, 0x0, ...)
        /home/ipkiss/.cache/yay/tmsu/src/TMSU-0.7.5/src/github.com/oniony/TMSU/cli/tag.go:145 +0xbfb
github.com/oniony/TMSU/cli.Run()
        /home/ipkiss/.cache/yay/tmsu/src/TMSU-0.7.5/src/github.com/oniony/TMSU/cli/cli.go:60 +0x3e4
main.main()
        /home/ipkiss/.cache/yay/tmsu/src/TMSU-0.7.5/src/github.com/oniony/TMSU/main.go:23 +0x20
```

**Comment by oniony** [comment]
Will add validation in Rust rewrite.
